"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env", override=True)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "unsafe-dev-key")#'django-insecure-g@jhm80upyy83+ab65e^&l=n=sr)!y)(om+c!)w08-*_^x2e@l'

def env_list(name, default=""):
    return [
        item.strip()
        for item in os.getenv(name, default).split(",")
        if item.strip()
    ]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", "127.0.0.1,localhost")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "rest_framework",
    "corsheaders",

    "common",
    "accounts",
    "patients",
    "appointments",
    "medical_records",
    "billing",
    "notifications",
    "legacy_hmis",
    "payments",
    "pacs",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",    
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME' : os.getenv("DB_NAME"),
        'HOST' : os.getenv("DB_HOST"),
        'USER' : os.getenv("DB_USER"),
        'PASSWORD' : os.getenv("DB_PASSWORD"),
        "PORT": os.getenv("DB_PORT", "3306"),
    },

    'legacy_hmis': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME' : os.getenv("DB2_NAME"),
        'HOST' : os.getenv("DB2_HOST"),
        'USER' : os.getenv("DB2_USER"),
        'PASSWORD' : os.getenv("DB2_PASSWORD"),
        "PORT": os.getenv("DB2_PORT", "3306"),
    }
}

DATABASE_ROUTERS = [
    "config.db_routers.LegacyHMISRouter",
]


# FTP Server

FTP_REPORT_HOST = os.getenv("FTP_REPORT_HOST", "").strip()
FTP_REPORT_PORT = int(os.getenv("FTP_REPORT_PORT", "21"))
FTP_REPORT_USER = os.getenv("FTP_REPORT_USER", "").strip()
FTP_REPORT_PASSWORD = os.getenv("FTP_REPORT_PASSWORD", "").strip()
FTP_REPORT_BASE_DIR = os.getenv("FTP_REPORT_BASE_DIR", "").strip()
FTP_REPORT_USE_TLS = os.getenv("FTP_REPORT_USE_TLS", "False").strip().lower() == "true"

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    "accounts.backends.PatientLegacyBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    "http://127.0.0.1:8080,http://localhost:8080"
)

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}



CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    "http://127.0.0.1:8080,http://localhost:8080"
)

CORS_ALLOW_CREDENTIALS = True

CSRF_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_HTTPONLY = False

# For local HTTP testing only
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False

#ConnectIPS
CONNECTIPS_BASE_URL = os.getenv("CONNECTIPS_BASE_URL", "").rstrip("/")
CONNECTIPS_MERCHANT_ID = os.getenv("CONNECTIPS_MERCHANT_ID", "")
CONNECTIPS_APP_ID = os.getenv("CONNECTIPS_APP_ID", "")
CONNECTIPS_APP_NAME = os.getenv("CONNECTIPS_APP_NAME", "")
CONNECTIPS_APP_PASSWORD = os.getenv("CONNECTIPS_APP_PASSWORD", "")

CONNECTIPS_PFX_PATH = os.getenv("CONNECTIPS_PFX_PATH", "")
CONNECTIPS_PFX_PASSWORD = os.getenv("CONNECTIPS_PFX_PASSWORD", "")

CONNECTIPS_CURRENCY = os.getenv("CONNECTIPS_CURRENCY", "NPR")

#PACS
import os

ORTHANC_BASE_URL = os.getenv("ORTHANC_BASE_URL", "http://127.0.0.1:8042")
ORTHANC_USERNAME = os.getenv("ORTHANC_USERNAME", "admin")
ORTHANC_PASSWORD = os.getenv("ORTHANC_PASSWORD", "admin123")
ORTHANC_TIMEOUT = 20
ORTHANC_PUBLIC_URL = os.getenv("ORTHANC_PUBLIC_URL", "").rstrip("/")

PACS_APP_BASE_URL = os.getenv("PACS_APP_BASE_URL", "").rstrip("/")
PACS_SEARCH_PARAM = os.getenv("PACS_SEARCH_PARAM", "accession")

PACS_PREVIEW_CACHE_DIR = os.path.join(BASE_DIR, "pacs_preview_cache")

# 1 hour temporary cache
PACS_PREVIEW_CACHE_TTL_SECONDS = int(
    os.getenv("PACS_PREVIEW_CACHE_TTL_SECONDS", "3600")
)