# dcoker-compose.yml
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: patportal_backend
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: patportal_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media

volumes:
  static_volume:
  media_volume:
