# Generated by Django 5.2.14 on 2026-06-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_hmis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblgrievances',
            fields=[
                ('fldid', models.BigAutoField(primary_key=True, serialize=False)),
                ('fldpatientval', models.CharField(blank=True, max_length=150, null=True)),
                ('fldptcontact', models.CharField(blank=True, max_length=150, null=True)),
                ('fldgrievance', models.TextField(blank=True, null=True)),
                ('fldstatus', models.CharField(blank=True, max_length=150, null=True)),
                ('fldresponse', models.TextField(blank=True, null=True)),
                ('fldtime', models.DateTimeField(blank=True, null=True)),
                ('flduserid', models.CharField(blank=True, max_length=25, null=True)),
                ('fldcomp', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tblgrievances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tblwebqueue',
            fields=[
                ('fldid', models.BigAutoField(primary_key=True, serialize=False)),
                ('fldgroup', models.CharField(blank=True, max_length=150, null=True)),
                ('fldscheme', models.CharField(blank=True, max_length=150, null=True)),
                ('flddepartment', models.CharField(blank=True, max_length=150, null=True)),
                ('fldqueue', models.IntegerField(blank=True, null=True)),
                ('fldconsultstart', models.DateTimeField(blank=True, null=True)),
                ('fldtime', models.DateTimeField(blank=True, null=True)),
                ('flduserid', models.CharField(blank=True, max_length=25, null=True)),
                ('fldcomp', models.CharField(blank=True, max_length=50, null=True)),
                ('fldsave', models.BooleanField(blank=True, null=True)),
                ('flduptime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblwebqueue',
                'managed': False,
            },
        ),
    ]
