# Generated by Django 5.2.14 on 2026-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsewaPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=150)),
                ('encounter_id', models.CharField(max_length=150)),
                ('payment_type', models.CharField(choices=[('BILL', 'Bill Payment'), ('DEPOSIT', 'Deposit')], max_length=20)),
                ('arc_code', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('transaction_uuid', models.CharField(max_length=150, unique=True)),
                ('booking_id', models.CharField(blank=True, max_length=250, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=250, null=True)),
                ('deeplink', models.TextField(blank=True, null=True)),
                ('esewa_status', models.CharField(choices=[('INITIATED', 'Initiated'), ('BOOKED', 'Booked'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('REVERTED', 'Reverted'), ('INVOICE_CREATED', 'Invoice Created'), ('DEPOSIT_CREATED', 'Deposit Created')], default='INITIATED', max_length=50)),
                ('reference_code', models.CharField(blank=True, max_length=150, null=True)),
                ('healthybit_invoice_no', models.CharField(blank=True, max_length=150, null=True)),
                ('healthybit_deposit_no', models.CharField(blank=True, max_length=150, null=True)),
                ('raw_request', models.JSONField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('callback_payload', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
