# Generated by Django 5.2.14 on 2026-06-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectIPSPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_id', models.CharField(max_length=150)),
                ('txn_id', models.CharField(max_length=20, unique=True)),
                ('reference_id', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paisa', models.IntegerField()),
                ('remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('particulars', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('ERROR', 'Error'), ('INCOMPLETE', 'Incomplete')], default='INITIATED', max_length=30)),
                ('connectips_status', models.CharField(blank=True, max_length=50, null=True)),
                ('status_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('nchl_txn_id', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('validation_request', models.JSONField(blank=True, null=True)),
                ('validation_response', models.JSONField(blank=True, null=True)),
                ('detail_response', models.JSONField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'connectips_payment_transaction',
            },
        ),
    ]
