# Generated by Django 5.2.14 on 2026-06-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_connectipspaymenttransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esewapaymenttransaction',
            name='payment_type',
            field=models.CharField(choices=[('BILL', 'Bill Payment'), ('DEPOSIT', 'Deposit'), ('APPOINTMENT', 'Appointment')], max_length=20),
        ),
    ]
