# Generated by Django 5.2.14 on 2026-06-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_esewapaymenttransaction_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectipspaymenttransaction',
            name='arc_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='connectipspaymenttransaction',
            name='encounter_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
