# Generated by Django 5.2.14 on 2026-06-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_connectips_add_encounter_arc_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhaltiPaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('patient_id', models.CharField(max_length=150)),
                ('encounter_id', models.CharField(blank=True, max_length=150, null=True)),
                ('arc_code', models.CharField(blank=True, max_length=250, null=True)),
                ('purchase_order_id', models.CharField(max_length=30, unique=True)),
                ('pidx', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paisa', models.IntegerField()),
                ('khalti_status', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], default='INITIATED', max_length=30)),
                ('transaction_id', models.CharField(blank=True, max_length=200, null=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('initiate_response', models.JSONField(blank=True, null=True)),
                ('lookup_response', models.JSONField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'khalti_payment_transaction',
            },
        ),
    ]
